services:
  - type: web
    name: skin-tone-analyzer
    env: python
    buildCommand: |
      set -e
      echo "Starting build process..."
      python -m pip install --upgrade pip
      
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      
      echo "Setting up package structure..."
      rm -rf skin_tone_analyzer/__pycache__
      mkdir -p skin_tone_analyzer
      
      echo "Copying skin_tone.py..."
      cp -f Python/skin_tone.py skin_tone_analyzer/skin_tone.py
      chmod 644 skin_tone_analyzer/skin_tone.py
      
      echo "Creating __init__.py..."
      cat > skin_tone_analyzer/__init__.py << 'EOL'
import os
import sys
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

try:
    from .skin_tone import process_image, detect_skin_tone, recommend_colors, create_color_preview
    logger.info("Successfully imported skin_tone module")
except ImportError as e:
    logger.error(f"Error importing from skin_tone: {e}")
    logger.error(f"Current directory: {os.getcwd()}")
    logger.error(f"Package directory: {os.path.dirname(os.path.abspath(__file__))}")
    logger.error(f"Directory contents: {os.listdir(os.path.dirname(os.path.abspath(__file__)))}")
    raise

__all__ = ['process_image', 'detect_skin_tone', 'recommend_colors', 'create_color_preview']
EOL
      chmod 644 skin_tone_analyzer/__init__.py
      
      echo "Installing dependencies..."
      pip install -r requirements.txt
      
      echo "Verifying package structure..."
      ls -la skin_tone_analyzer/
      
      echo "Installing package..."
      pip install -e .
      
      echo "Creating uploads directory..."
      mkdir -p uploads
      chmod 755 uploads
      
      echo "Verifying imports..."
      PYTHONPATH=/opt/render/project/src python -c "from skin_tone_analyzer import process_image; print('Import successful')"
      
      echo "Build completed successfully"
    startCommand: |
      gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 --access-logfile - --error-logfile - wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: GUNICORN_CMD_ARGS
        value: "--log-level=info"
    autoDeploy: true
    healthCheckPath: /
    plan: free