services:
  - type: web
    name: skin-tone-analyzer
    env: python
    buildCommand: |
      set -e
      echo "Starting build process..."
      python -m pip install --upgrade pip
      
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      
      echo "Installing dependencies..."
      pip install -r requirements.txt
      
      echo "Installing package..."
      pip install -e .
      
      echo "Verifying package structure..."
      ls -la skin_tone_analyzer/
      
      echo "Verifying skin_tone.py exists..."
      if [ ! -f "skin_tone_analyzer/skin_tone.py" ]; then
        echo "ERROR: skin_tone.py not found in package directory"
        exit 1
      fi
      
      echo "Verifying imports..."
      python -c "from skin_tone_analyzer import process_image; print('Import successful')"
      
      echo "Build completed successfully"
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    autoDeploy: true
    healthCheckPath: /
    plan: free