services:
  - type: web
    name: skin-tone-analyzer
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /
    plan: free