services:
  - type: web
    name: skin-tone-analyzer
    env: python
    buildCommand: |
      echo "Starting build process..."
      python -m pip install --upgrade pip
      echo "Creating package directory..."
      mkdir -p skin_tone_analyzer
      echo "Creating __init__.py..."
      cp -f skin_tone_analyzer/__init__.py skin_tone_analyzer/__init__.py
      echo "Copying skin_tone.py..."
      cp -f Python/skin_tone.py skin_tone_analyzer/skin_tone.py
      echo "Verifying package structure..."
      ls -la skin_tone_analyzer/
      echo "Installing package..."
      pip install -e .
      echo "Verifying installation..."
      python -c "import skin_tone_analyzer.skin_tone; print('Import successful')"
      echo "Build completed successfully"
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /
    plan: free