services:
  - type: web
    name: skin-tone-analyzer
    env: python
    buildCommand: |-
      set -ex
      python -m pip install --upgrade pip
      
      # Set up package structure
      mkdir -p skin_tone_analyzer
      cp Python/skin_tone.py skin_tone_analyzer/skin_tone.py
      
      # Install dependencies
      pip install -r requirements.txt
      
      # Install the package
      python setup.py install
      
      # Create uploads directory
      mkdir -p uploads
      
      # Verify installation
      python -c "import skin_tone_analyzer; print('Import successful')"
    startCommand: python -m gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_ENV
        value: production
    buildFilter:
      paths:
      - Python/**
      - skin_tone_analyzer/**
      - requirements.txt
      - setup.py
      - wsgi.py
      - app.py
      - templates/**
      - render.yaml
    autoDeploy: true
    healthCheckPath: /
    plan: free