services:
  - type: web
    name: skin-tone-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: MAX_CONTENT_LENGTH
        value: 16777216  # 16MB max-body-size
    healthCheckPath: /
    plan: free