services:
  - type: web
    name: skin-tone-analyzer
    env: python
    buildCommand: |
      python -m pip install --upgrade pip && \
      pip install -r requirements.txt && \
      mkdir -p skin_tone_analyzer && \
      cp Python/skin_tone.py skin_tone_analyzer/ && \
      touch skin_tone_analyzer/__init__.py && \
      pip install -e .
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PYTHONPATH
        value: .
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
    autoDeploy: true
    healthCheckPath: /
    plan: free