services:
  - type: web
    name: skin-tone-analyzer
    env: python
    buildCommand: |
      set -e && \
      python -m pip install --upgrade pip && \
      pip install -r requirements.txt && \
      mkdir -p skin_tone_analyzer && \
      cp -f Python/skin_tone.py skin_tone_analyzer/ && \
      touch skin_tone_analyzer/__init__.py && \
      ls -la skin_tone_analyzer/ && \
      pip install -e . && \
      echo "Build completed successfully"
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: 1
    autoDeploy: true
    healthCheckPath: /
    plan: free